"""Локализованные подписи кнопок UI (полный i18n)."""

from __future__ import annotations

from bot.texts.i18n import LANGS, DEFAULT_LANG, normalize_lang, lang_of

# action → lang → label
MENU: dict[str, dict[str, str]] = {
    "rate": {"ru": "Оценивать❤️", "be": "Ацэньваць❤️", "uk": "Оцінювати❤️", "kk": "Бағалау❤️"},
    "events": {"ru": "Тусовки🥳", "be": "Тусоўкі🥳", "uk": "Тусовки🥳", "kk": "Тусовкалар🥳"},
    "profile": {"ru": "Профиль👤", "be": "Профіль👤", "uk": "Профіль👤", "kk": "Профиль👤"},
    "goals": {"ru": "Цели✨", "be": "Мэты✨", "uk": "Цілі✨", "kk": "Мақсаттар✨"},
    "luma": {"ru": "Лума🤵🏼‍♀️", "be": "Лума🤵🏼‍♀️", "uk": "Лума🤵🏼‍♀️", "kk": "Лума🤵🏼‍♀️"},
    "menu": {"ru": "Меню", "be": "Меню", "uk": "Меню", "kk": "Меню"},
}

# Канонические имена из БД (ru) → подписи UI
EVENT_CATEGORIES: dict[str, dict[str, str]] = {
    "Сегодня": {"ru": "Сегодня", "be": "Сёння", "uk": "Сьогодні", "kk": "Бүгін"},
    "Рядом": {"ru": "Рядом", "be": "Пабач", "uk": "Поруч", "kk": "Жақын"},
    "На хату": {"ru": "На хату", "be": "На хату", "uk": "На хату", "kk": "Үйге"},
    "Праздники": {"ru": "Праздники", "be": "Святы", "uk": "Свята", "kk": "Мерекелер"},
    "Игры": {"ru": "Игры", "be": "Гульні", "uk": "Ігри", "kk": "Ойындар"},
    "Посиделки": {"ru": "Посиделки", "be": "Пасядзелкі", "uk": "Посиденьки", "kk": "Басқосу"},
}

INLINE: dict[str, dict[str, str]] = {
    "prof_age": {"ru": "Изменить возраст😉", "be": "Змяніць узрост😉", "uk": "Змінити вік😉", "kk": "Жасты өзгерту😉"},
    "prof_gender": {"ru": "Выбрать пол 👫", "be": "Абраць пол 👫", "uk": "Обрати стать 👫", "kk": "Жынысты таңдау 👫"},
    "prof_photo": {"ru": "Изменить фото 📸", "be": "Змяніць фота 📸", "uk": "Змінити фото 📸", "kk": "Фотоны өзгерту 📸"},
    "prof_city": {"ru": "Выбрать город 🌉", "be": "Абраць горад 🌉", "uk": "Обрати місто 🌉", "kk": "Қаланы таңдау 🌉"},
    "prof_bio": {"ru": "Изменить описание📝", "be": "Змяніць апісанне📝", "uk": "Змінити опис📝", "kk": "Сипаттаманы өзгерту📝"},
    "prof_premium": {"ru": "Premium👑", "be": "Premium👑", "uk": "Premium👑", "kk": "Premium👑"},
    "prof_disable": {"ru": "Отключить анкету🔇", "be": "Адключыць анкету🔇", "uk": "Вимкнути анкету🔇", "kk": "Анкетаны өшіру🔇"},
    "prof_enable": {"ru": "Включить анкету", "be": "Уключыць анкету", "uk": "Увімкнути анкету", "kk": "Анкетаны қосу"},
    "prof_referral": {"ru": "Реферальная программа💸", "be": "Рэферальная праграма💸", "uk": "Реферальна програма💸", "kk": "Реферал бағдарламасы💸"},
    "prof_lang": {"ru": "Язык👋🏻", "be": "Мова👋🏻", "uk": "Мова👋🏻", "kk": "Тіл👋🏻"},
    "prof_verify": {"ru": "Верификация🤵", "be": "Верыфікацыя🤵", "uk": "Верифікація🤵", "kk": "Верификация🤵"},
    "prof_withdraw": {"ru": "Вывести искры🔃", "be": "Вывесці іскры🔃", "uk": "Вивести іскри🔃", "kk": "Ұшқын шығару🔃"},
    "prof_buy": {"ru": "Купить искры💵", "be": "Купіць іскры💵", "uk": "Купити іскри💵", "kk": "Ұшқын сатып алу💵"},
    "prof_reset": {"ru": "Сбросить рейтинг📈", "be": "Скінуць рэйтынг📈", "uk": "Скинути рейтинг📈", "kk": "Рейтингті тастау📈"},
    "goal_change": {"ru": "Поменять цель", "be": "Змяніць мэту", "uk": "Змінити ціль", "kk": "Мақсатты өзгерту"},
    "goal_withdraw": {"ru": "Вывести в искры", "be": "Вывесці ў іскры", "uk": "Вивести в іскри", "kk": "Ұшқынға шығару"},
    "ev_create": {"ru": "Создать тусовку", "be": "Стварыць тусоўку", "uk": "Створити тусовку", "kk": "Тусовка жасау"},
    "ev_my": {"ru": "Мои тусовки", "be": "Мае тусоўкі", "uk": "Мої тусовки", "kk": "Менің тусовкаларым"},
    "ev_find": {"ru": "Найти тусовку", "be": "Знайсці тусоўку", "uk": "Знайти тусовку", "kk": "Тусовка табу"},
    "ev_apply": {"ru": "Подать заявку", "be": "Падаць заяўку", "uk": "Подати заявку", "kk": "Өтінім беру"},
    "ev_next": {"ru": "Следующая", "be": "Наступная", "uk": "Наступна", "kk": "Келесі"},
    "ev_share": {"ru": "Поделиться", "be": "Падзяліцца", "uk": "Поділитися", "kk": "Бөлісу"},
    "ev_report": {"ru": "Жалоба", "be": "Скарга", "uk": "Скарга", "kk": "Шағым"},
    "ev_boost": {"ru": "⬆️ В ТОП", "be": "⬆️ У ТОП", "uk": "⬆️ В ТОП", "kk": "⬆️ ТОП"},
    "ev_pin": {"ru": "📌 Закреп", "be": "📌 Замацаваць", "uk": "📌 Закріпити", "kk": "📌 Бекіту"},
    "ev_boost_price": {"ru": "⬆️ В ТОП ({price}⚡)", "be": "⬆️ У ТОП ({price}⚡)", "uk": "⬆️ В ТОП ({price}⚡)", "kk": "⬆️ ТОП ({price}⚡)"},
    "ev_boost_free": {"ru": "⬆️ В ТОП (бесплатно)", "be": "⬆️ У ТОП (бясплатна)", "uk": "⬆️ В ТОП (безкоштовно)", "kk": "⬆️ ТОП (тегін)"},
    "ev_pin_price": {"ru": "📌 Закреп ({price}⚡/ч)", "be": "📌 Замацаваць ({price}⚡/г)", "uk": "📌 Закріпити ({price}⚡/год)", "kk": "📌 Бекіту ({price}⚡/сағ)"},
    "reset_rating_price": {"ru": "Сбросить рейтинг за {price} искр", "be": "Скінуць рэйтынг за {price} іскраў", "uk": "Скинути рейтинг за {price} іскор", "kk": "Рейтингті {price} ұшқынға тастау"},
    "reset_rating_free": {"ru": "Сбросить рейтинг бесплатно", "be": "Скінуць рэйтынг бясплатна", "uk": "Скинути рейтинг безкоштовно", "kk": "Рейтингті тегін тастау"},
    "wd_stars": {"ru": "⭐ Telegram Stars", "be": "⭐ Telegram Stars", "uk": "⭐ Telegram Stars", "kk": "⭐ Telegram Stars"},
    "wd_requisites": {"ru": "💳 Реквизиты", "be": "💳 Рэквізіты", "uk": "💳 Реквізити", "kk": "💳 Реквизиттер"},
    "like": {"ru": "❤️ Лайк", "be": "❤️ Лайк", "uk": "❤️ Лайк", "kk": "❤️ Лайк"},
    "comment": {"ru": "💬 С комментарием", "be": "💬 З каментарыем", "uk": "💬 З коментарем", "kk": "💬 Пікірмен"},
    "support": {"ru": "⚡ Поддержать", "be": "⚡ Падтрымаць", "uk": "⚡ Підтримати", "kk": "⚡ Қолдау"},
    "skip": {"ru": "⏭ Следующая", "be": "⏭ Наступная", "uk": "⏭ Наступна", "kk": "⏭ Келесі"},
    "anon": {"ru": "Анонимно", "be": "Ананімна", "uk": "Анонімно", "kk": "Аноним"},
    "open": {"ru": "Открыто", "be": "Адкрыта", "uk": "Відкрито", "kk": "Ашық"},
    "luma_people": {"ru": "🔍 Поиск людей", "be": "🔍 Пошук людзей", "uk": "🔍 Пошук людей", "kk": "🔍 Адам іздеу"},
    "luma_events": {"ru": "🎉 Поиск тусовок", "be": "🎉 Пошук тусовак", "uk": "🎉 Пошук тусовок", "kk": "🎉 Тусовка іздеу"},
    "luma_ask": {"ru": "💬 Задать вопрос", "be": "💬 Задаць пытанне", "uk": "💬 Задати питання", "kk": "💬 Сұрақ қою"},
    "buy_premium": {"ru": "Купить Premium", "be": "Купіць Premium", "uk": "Купити Premium", "kk": "Premium сатып алу"},
    "invite_friends": {"ru": "Пригласить друзей", "be": "Запрасіць сяброў", "uk": "Запросити друзів", "kk": "Достарды шақыру"},
    "back": {"ru": "« Назад", "be": "« Назад", "uk": "« Назад", "kk": "« Артқа"},
    "yes_delete": {"ru": "Да, удалить", "be": "Так, выдаліць", "uk": "Так, видалити", "kk": "Иә, жою"},
    "cancel": {"ru": "Отмена", "be": "Адмена", "uk": "Скасувати", "kk": "Болдырмау"},
    "yes_close": {"ru": "Да, закрыть", "be": "Так, закрыць", "uk": "Так, закрити", "kk": "Иә, жабу"},
    "write_tg": {"ru": "✍️ Написать в Telegram", "be": "✍️ Напісаць у Telegram", "uk": "✍️ Написати в Telegram", "kk": "✍️ Telegram-да жазу"},
    "admin_open": {"ru": "Открыть админ-панель", "be": "Адкрыць адмін-панэль", "uk": "Відкрити адмін-панель", "kk": "Админ-панельді ашу"},
    "no": {"ru": "Нет", "be": "Не", "uk": "Ні", "kk": "Жоқ"},
    "no_exact": {"ru": "Точно нет", "be": "Дакладна не", "uk": "Точно ні", "kk": "Нақты жоқ"},
    "no_rather": {"ru": "Скорее нет", "be": "Хутчэй не", "uk": "Скоріше ні", "kk": "Жоқ дерсің"},
    "yes": {"ru": "Да", "be": "Так", "uk": "Так", "kk": "Иә"},
    "stay": {"ru": "Ладно, я остаюсь", "be": "Добра, застаюся", "uk": "Добре, залишаюсь", "kk": "Жарайды, қаламын"},
    "goodbye": {"ru": "До встречи", "be": "Да сустрэчы", "uk": "До зустрічі", "kk": "Кездескенше"},
    "pay_yookassa": {"ru": "ЮKassa (₽)", "be": "ЮKassa (₽)", "uk": "ЮKassa (₽)", "kk": "ЮKassa (₽)"},
    "pay_stars": {"ru": "Telegram Stars (⭐)", "be": "Telegram Stars (⭐)", "uk": "Telegram Stars (⭐)", "kk": "Telegram Stars (⭐)"},
    "pay_now": {"ru": "💳 Оплатить", "be": "💳 Аплаціць", "uk": "💳 Оплатити", "kk": "💳 Төлеу"},
    "pay_stub": {"ru": "Симулировать оплату (демо)", "be": "Сімуляваць аплату (дэма)", "uk": "Симулювати оплату (демо)", "kk": "Төлемді симуляциялау (демо)"},
    "pay_check": {"ru": "Проверить оплату", "be": "Праверыць аплату", "uk": "Перевірити оплату", "kk": "Төлемді тексеру"},
    "sparks_amount_btn": {"ru": "Указать количество", "be": "Указаць колькасць", "uk": "Вказати кількість", "kk": "Санын көрсету"},
    "reset_rating_50": {"ru": "Сбросить рейтинг за 50 искр", "be": "Скінуць рэйтынг за 50 іскраў", "uk": "Скинути рейтинг за 50 іскор", "kk": "Рейтингті 50 ұшқынға тастау"},
    "ref_standard": {"ru": "Стандарт", "be": "Стандарт", "uk": "Стандарт", "kk": "Стандарт"},
    "ref_blogger": {"ru": "Блогер", "be": "Блогер", "uk": "Блогер", "kk": "Блогер"},
    "ref_info": {"ru": "Инфо", "be": "Інфа", "uk": "Інфо", "kk": "Ақпарат"},
    "ref_claim": {"ru": "Забрать награды", "be": "Забраць узнагароды", "uk": "Забрати нагороди", "kk": "Марапат алу"},
    "rate_next": {"ru": "Следующая", "be": "Наступная", "uk": "Наступна", "kk": "Келесі"},
    "rate_write": {"ru": "Написать", "be": "Напісаць", "uk": "Написати", "kk": "Жазу"},
    "rate_support": {"ru": "Поддержать", "be": "Падтрымаць", "uk": "Підтримати", "kk": "Қолдау"},
    "rate_report": {"ru": "Жалоба", "be": "Скарга", "uk": "Скарга", "kk": "Шағым"},
    "like_view_yes": {"ru": "👀 Да, посмотреть", "be": "👀 Так, паглядзець", "uk": "👀 Так, подивитись", "kk": "👀 Иә, қарау"},
    "like_later": {"ru": "Позже", "be": "Пазней", "uk": "Пізніше", "kk": "Кейінірек"},
    "back_list": {"ru": "« К списку", "be": "« Да спісу", "uk": "« До списку", "kk": "« Тізімге"},
    "ev_parts": {"ru": "Участники", "be": "Удзельнікі", "uk": "Учасники", "kk": "Қатысушылар"},
    "ev_invite": {"ru": "Пригласить людей", "be": "Запрасіць людзей", "uk": "Запросити людей", "kk": "Адамдарды шақыру"},
    "ev_apps": {"ru": "Заявки", "be": "Заяўкі", "uk": "Заявки", "kk": "Өтінімдер"},
    "ev_close_chat": {"ru": "Закрыть набор (чат)", "be": "Закрыць набор (чат)", "uk": "Закрити набір (чат)", "kk": "Жинақты жабу (чат)"},
    "ev_edit": {"ru": "Редактировать", "be": "Рэдагаваць", "uk": "Редагувати", "kk": "Өңдеу"},
    "ev_delete": {"ru": "Удалить", "be": "Выдаліць", "uk": "Видалити", "kk": "Жою"},
    "ev_open": {"ru": "Открыть", "be": "Адкрыць", "uk": "Відкрити", "kk": "Ашу"},
    "pay_fee": {"ru": "Оплатить взнос · {price} ⚡", "be": "Аплаціць узнос · {price} ⚡", "uk": "Оплатити внесок · {price} ⚡", "kk": "Жарна төлеу · {price} ⚡"},
    "fee_paid": {"ru": "✅ Взнос оплачен", "be": "✅ Узнос аплачаны", "uk": "✅ Внесок оплачено", "kk": "✅ Жарна төленді"},
    "pay_confirm": {"ru": "✅ Оплатить", "be": "✅ Аплаціць", "uk": "✅ Оплатити", "kk": "✅ Төлеу"},
    "edit_title": {"ru": "Название", "be": "Назва", "uk": "Назва", "kk": "Атауы"},
    "edit_city": {"ru": "Город", "be": "Горад", "uk": "Місто", "kk": "Қала"},
    "edit_address": {"ru": "Адрес", "be": "Адрас", "uk": "Адреса", "kk": "Мекенжай"},
    "edit_datetime": {"ru": "Дата/время", "be": "Дата/час", "uk": "Дата/час", "kk": "Күні/уақыты"},
    "edit_price": {"ru": "Цена", "be": "Цана", "uk": "Ціна", "kk": "Бағасы"},
    "edit_desc": {"ru": "Описание", "be": "Апісанне", "uk": "Опис", "kk": "Сипаттама"},
    "edit_photo": {"ru": "Фото", "be": "Фота", "uk": "Фото", "kk": "Фото"},
    "inv_link": {"ru": "Ссылка на тусовку", "be": "Спасылка на тусоўку", "uk": "Посилання на тусовку", "kk": "Тусовка сілтемесі"},
    "inv_mass": {"ru": "Массовое приглашение (Premium)", "be": "Масавае запрашэнне (Premium)", "uk": "Масове запрошення (Premium)", "kk": "Жаппай шақыру (Premium)"},
    "app_accept": {"ru": "Принять", "be": "Прыняць", "uk": "Прийняти", "kk": "Қабылдау"},
    "app_reject": {"ru": "Отклонить", "be": "Адхіліць", "uk": "Відхилити", "kk": "Қабылдамау"},
}

EXTRA_TEXTS: dict[str, dict[str, str]] = {
    "ru": {
        "MENU_TITLE": "Меню:",
        "WITHDRAW_CHOOSE_METHOD": "Как вывести Искры?\n\n⭐ Telegram Stars — выплата подарками Stars на твой аккаунт\n💳 Реквизиты — карта / телефон / другой способ",
        "WITHDRAW_AMOUNT": "Укажи количество Искр для вывода:",
        "WITHDRAW_CREATED_STARS": (
            "Заявка #{id}: вывод {amount} Искр через Stars.\n"
            "К выплате: {net} Stars (комиссия {fee}).\n"
            "{status_line}"
        ),
        "WITHDRAW_CREATED_REQ": (
            "Заявка #{id}: вывод {amount} Искр на реквизиты.\n"
            "К выплате: {net} (комиссия {fee}).\n"
            "Обработка до 24 часов."
        ),
        "WITHDRAW_STARS_OK": "✅ Stars выплачены ({gifts} подарков, {stars}⭐).",
        "WITHDRAW_STARS_PENDING": "⏳ Автовыплата Stars не прошла: {error}\nАдмин обработает заявку вручную.",
        "WITHDRAW_ASK_REQUISITES": "Укажи реквизиты (карта / телефон / другой способ).\nСумма: {amount} Искр",
        "EVENT_ASK_CATEGORY": "Выбери тематику тусовки:",
        "EVENT_CREATED": "Тусовка «{title}» создана!",
        "EVENT_ASK_TITLE": "Название тусовки:",
        "EVENT_ASK_CITY": "Город:",
        "EVENT_ASK_ADDRESS": "Место проведения:",
        "EVENT_ASK_DATETIME": "Дата и время (например: 25.07.2026 19:00):",
        "EVENT_ASK_PRICE": "Сколько скидываться:",
        "EVENT_ASK_MEN": "Сколько парней нужно:",
        "EVENT_ASK_WOMEN": "Сколько девушек нужно:",
        "EVENT_ASK_PHOTO": "Фото тусовки:",
        "EVENT_ASK_DESC": "Описание:",
        "NO_GOAL": "У тебя пока нет цели.",
        "PHOTO_ASK": "Отправь мне свое фото",
        "CITY_ASK": "Переехал? Из какого ты города?",
        "SPARKS_TRANSFERRED": "Переведено {amount} Искр на баланс.",
        "EVENT_NOT_FOUND": "Тусовка не найдена или удалена.",
        "EVENT_CLOSED": "Тусовка «{title}» уже закрыта.",
        "EVENT_NONE": "У тебя пока нет тусовок.",
        "EVENT_PICK": "Выбери тусовку:",
        "EVENT_EMPTY_CAT": "Пока нет тусовок в этой категории.",
        "EVENT_EMPTY_TODAY": "На сегодня тусовок пока нет.",
        "EVENT_EMPTY_NEAR": "Рядом тусовок нет. Укажи город в профиле или загляни позже.",
        "EVENT_NO_MORE": "Больше тусовок нет.",
        "EVENT_SHARE": "Ссылка на тусовку:\n{link}\n\nОткрой ссылку — откроется карточка.",
        "EVENT_NO_APPS": "Нет заявок.",
        "EVENT_INVITE_PEOPLE": "Пригласить людей:",
        "EVENT_PARTS_EMPTY": "Участники «{title}»:\n\nПока никого нет.",
        "EVENT_PARTS_LIST": "Участники «{title}» ({count}):\nНажми кнопку, чтобы открыть профиль.",
        "EVENT_EDIT_WHAT": "Что изменить в «{title}»?",
        "EVENT_SAVED": "Сохранено.",
        "EVENT_PHOTO_UPDATED": "Фото обновлено.",
        "EVENT_NEED_TEXT": "Сейчас нужно текстовое значение.",
        "EVENT_NEED_PHOTO": "Пришли фото.",
        "EVENT_APP_SENT": "Заявка отправлена!",
        "EVENT_APP_ALREADY": "Ты уже подал заявку",
        "EVENT_APP_ACCEPTED_STATUS": "Ты уже в списке участников",
        "EVENT_APP_PENDING": "Ты уже подал заявку",
        "EVENT_APP_REJECTED_STATUS": "Заявка ранее отклонена",
        "EVENT_FEE_NONE": "Взнос не требуется",
        "EVENT_FEE_PAID": "Взнос уже оплачен",
        "EVENT_FEE_NEED_ACCEPT": "Сначала нужно быть принятым",
        "EVENT_ORG_MISSING": "Организатор не найден",
        "EVENT_FEE_CONFIRM": (
            "Оплатить взнос за «{title}»?\n\n"
            "Сумма: {price} искр\n"
            "Баланс: {balance} искр\n\n"
            "Искры будут переведены организатору."
        ),
        "EVENT_FEE_DONE": "Взнос оплачен!",
        "EVENT_NOT_ENOUGH": "Недостаточно Искр. Нужно {need}, у тебя {have}",
        "PREMIUM_ACTIVATED": "Premium активирован на 1 месяц!",
        "PROFILE_DISABLED_BYE": "Анкета отключена. До встречи!",
        "REF_NO_REWARDS": "Нет доступных наград",
        "REF_CLAIMED": "Награда получена: {reward}",
        "REF_INVITED_LINE": "Приглашено: {count}",
        "BUY_SPARKS_ASK": "Сколько Искр хотите купить?",
        "BUY_PREMIUM_BTN": "Купить подписку за {price} 🌙",
        "WITHDRAW_MIN": "Минимальная сумма вывода — {min} Искр",
        "RATING_RESET_FREE": "Рейтинг сброшен бесплатно (Premium).",
        "RATING_RESET_OK": "Рейтинг сброшен.",
        "VERIFY_ALREADY": "Ты уже верифицирован",
        "VERIFY_NEED_CIRCLE": "Отправь видеосообщение (кружок) с лицом, кодом и жестом.",
        "PAY_NOT_STUB": "Это не демо-платёж",
        "PAY_ALREADY": "Уже зачислено",
        "EVGROUP_HINT": "Набор закрыт. Создайте групповой чат — список участников отправлен.",
        "EDIT_FIELD_UNKNOWN": "Неизвестное поле",
        "EDIT_ASK_TITLE": "Название тусовки:",
        "EDIT_ASK_CITY": "Город:",
        "EDIT_ASK_ADDRESS": "Место проведения:",
        "EDIT_ASK_DATETIME": "Дата и время (например: 25.07.2026 19:00):",
        "EDIT_ASK_PRICE": "Сколько скидываться:",
        "EDIT_ASK_DESC": "Описание:",
        "EDIT_ASK_PHOTO": "Пришли новое фото тусовки:",

        "PROFILE_OWN": "👋 Имя: {name}, {age}{premium}{verified}\n{bio}\n⚡ Искры: {sparks}\n🌟 Рейтинг: {rating}/5\n👥 Вас оценили {rated} человек\n🎉 Тусовок посетил: {attended}\n😎 Тусовок организовал: {organized}\n{goal}\nВаш пол: {gender}\nКого вы хотите оценивать: {seeking}\nКем вы хотите быть оценены: {visible}\n🌆 Город: {city}",
        "PROFILE_GOAL_OWN": "⚡️Цель: {title}",
        "PROFILE_OTHER": "{name}, {age}{badges}\n{bio}\n🌟 Рейтинг: {rating}/5 ({rated})\n🎉 Тусовок посетил: {attended}\n🥳 Тусовок организовал: {organized}\n🎯 Цель: {goal}\n🌆 Город: {city}",
        "PROFILE_GOAL_OTHER": "{title} · {collected}/{target} (осталось {remaining}, {percent}%)",
        "EVENT_CARD": "🔥 {title}{pin}{boost}\n🏷 {category}\n📍 {city}, {address}\n🕐 {date}, {time}\n👥 {men_label}: {men_count}/{men_needed}  👩 {women_label}: {women_count}/{women_needed}\n💰 {price}{org}\n{description}",
        "EVENT_DEFAULT_CAT": "Тусовка",
        "EVENT_MEN": "Парни",
        "EVENT_WOMEN": "Девушки",
        "EVENT_ROLE_ORG": "Организатор:\n{meta}",
        "EVENT_ROLE_ATTEND": "Участвуешь:\n{meta}{fee_line}",
        "EVENT_FEE_LINE": "\n💰 Взнос: {price} искр",
        "EVENT_FEE_LINE_PAID": "\n💰 Взнос: {price} искр · оплачен ✅",
        "EVENT_FEE_PAID_NOTIFY": "💰 {name} оплатил(а) взнос {price} искр за «{title}».",
        "EVENT_NEW_APP": "📩 Новая заявка на «{title}»",
        "EVENT_MANAGE_HEADER": "{mark} Организатор: «{title}»\n📍 {city} · {date} {time}",
        "EVENT_GENDER_M": "М",
        "EVENT_GENDER_F": "Ж",
        "MASS_INVITE": "🎉 Приглашение на тусовку «{title}»\n📍 {city}, {address}\n🕐 {date} {time}\nОткрыть: {link}",
        "EVENT_CLOSED_ROSTER": "🔒 Набор на «{title}» закрыт.\n\nОрганизатор: {org}\nУчастники:\n{roster}\n\nСоздайте групповой чат и добавьте всех.\nСлужебная ссылка: {link}",
        "BUY_SPARKS_TITLE": "Покупка Искр",
        "BUY_SPARKS_DESC": "Покупка {amount} Искр",
        "BUY_SPARKS_LABEL": "Искры",
        "YEARS_ONE": "год",
        "YEARS_FEW": "года",
        "YEARS_MANY": "лет",
        "GENDER_male": "мужской",
        "GENDER_female": "женский",
        "GENDER_other": "другой",
        "SEEKING_men": "мужской",
        "SEEKING_women": "женский",
        "SEEKING_both": "оба",
        "VISIBLE_men": "мужской",
        "VISIBLE_women": "женский",
        "VISIBLE_all": "все",
        "ERR_ONLY_PREMIUM": "Только для Premium",
        "ERR_ONLY_ORG": "Только организатор",
        "ERR_MASS_LIMIT": "Лимит массовых приглашений исчерпан",
        "ERR_USER_NOT_FOUND": "Пользователь не найден",
        "ERR_FEE_NONE": "Взнос не требуется",
        "ERR_FEE_SELF": "Нельзя оплатить взнос самому себе",
        "ERR_FEE_PAID": "Взнос уже оплачен",
        "ERR_NO_GOAL_SPARKS": "Нет Искр для перевода с цели",
        "ERR_REWARD_UNAVAILABLE": "Награда недоступна",
        "ERR_WITHDRAW_METHOD": "Неверный способ вывода",
        "ERR_REQUISITES": "Укажи реквизиты для перевода подробнее",
        "ERR_EVENT_INACTIVE": "Тусовка не активна",
        "ERR_BOOST_ORG": "Только организатор может поднять тусовку",
        "ERR_PIN_ORG": "Только организатор может закрепить тусовку",
        "ERR_SUPPORT_SPARKS": "Недостаточно Искр для поддержки",
        "LUMA_PEOPLE_EMPTY": "Никого не нашла по запросу. Попробуй уточнить город или интересы.",
        "LUMA_PEOPLE_DONE": "Это все анкеты по запросу. Можешь поискать ещё или задать вопрос LUMA.",
        "LUMA_PEOPLE_FOUND": "Нашла людей:",
        "LUMA_EVENTS_EMPTY": "Тусовок по запросу не нашла. Попробуй другие ключевые слова.",
        "LUMA_EVENTS_DONE": "Это все тусовки по запросу. Можешь поискать ещё или задать вопрос LUMA.",
        "LUMA_EVENTS_FOUND": "Нашла тусовки:",
        "LUMA_EVENT_LINE": "• «{title}» — {city}, {date} {time}\n  {address} · места {taken}/{need}",
    },
    "be": {
        "MENU_TITLE": "Меню:",
        "WITHDRAW_CHOOSE_METHOD": "Як вывесці Іскры?\n\n⭐ Stars — на твой акаўнт\n💳 Рэквізіты — карта / тэлефон",
        "WITHDRAW_AMOUNT": "Колькі Іскраў вывесці:",
        "WITHDRAW_CREATED_STARS": "Заяўка #{id}: {amount} Іскраў праз Stars. Да выплаты: {net} (камісія {fee}).\n{status_line}",
        "WITHDRAW_CREATED_REQ": "Заяўка #{id}: {amount} Іскраў на рэквізіты. Да выплаты: {net} (камісія {fee}).",
        "WITHDRAW_STARS_OK": "✅ Stars выплачаны ({gifts} падарункаў, {stars}⭐).",
        "WITHDRAW_STARS_PENDING": "⏳ Аўтавыплата не прайшла: {error}",
        "WITHDRAW_ASK_REQUISITES": "Укажы рэквізіты. Сума: {amount} Іскраў",
        "EVENT_ASK_CATEGORY": "Абяры тэматыку тусоўкі:",
        "EVENT_CREATED": "Тусоўка «{title}» створана!",
        "EVENT_ASK_TITLE": "Назва тусоўкі:",
        "EVENT_ASK_CITY": "Горад:",
        "EVENT_ASK_ADDRESS": "Месца:",
        "EVENT_ASK_DATETIME": "Дата і час (напр. 25.07.2026 19:00):",
        "EVENT_ASK_PRICE": "Колькі скідвацца:",
        "EVENT_ASK_MEN": "Колькі хлопцаў:",
        "EVENT_ASK_WOMEN": "Колькі дзяўчат:",
        "EVENT_ASK_PHOTO": "Фота тусоўкі:",
        "EVENT_ASK_DESC": "Апісанне:",
        "NO_GOAL": "У цябе пакуль няма мэты.",
        "PHOTO_ASK": "Дашлі сваё фота",
        "CITY_ASK": "З якога ты горада?",
        "SPARKS_TRANSFERRED": "Пераведзена {amount} Іскраў на баланс.",
        "EVENT_NOT_FOUND": "Тусоўка не знойдзена.",
        "EVENT_CLOSED": "Тусоўка «{title}» ўжо закрыта.",
        "EVENT_NONE": "У цябе пакуль няма тусовак.",
        "EVENT_PICK": "Абяры тусоўку:",
        "EVENT_EMPTY_CAT": "Пакуль няма тусовак у гэтай катэгорыі.",
        "EVENT_EMPTY_TODAY": "На сёння тусовак пакуль няма.",
        "EVENT_EMPTY_NEAR": "Пабач тусовак няма. Пазнач горад у профілі або зазірні пазней.",
        "EVENT_NO_MORE": "Больш тусовак няма.",
        "EVENT_SHARE": "Спасылка:\n{link}",
        "EVENT_NO_APPS": "Няма заявак.",
        "EVENT_INVITE_PEOPLE": "Запрасіць людзей:",
        "EVENT_PARTS_EMPTY": "Удзельнікі «{title}»:\n\nПакуль нікога.",
        "EVENT_PARTS_LIST": "Удзельнікі «{title}» ({count}):",
        "EVENT_EDIT_WHAT": "Што змяніць у «{title}»?",
        "EVENT_SAVED": "Захавана.",
        "EVENT_PHOTO_UPDATED": "Фота абноўлена.",
        "EVENT_NEED_TEXT": "Зараз патрэбен тэкст.",
        "EVENT_NEED_PHOTO": "Дашлі фота.",
        "EVENT_APP_SENT": "Заяўка адпраўлена!",
        "EVENT_APP_ALREADY": "Ты ўжо падаў заяўку",
        "EVENT_APP_ACCEPTED_STATUS": "Ты ўжо ў спісе ўдзельнікаў",
        "EVENT_APP_PENDING": "Ты ўжо падаў заяўку",
        "EVENT_APP_REJECTED_STATUS": "Заяўка раней адхілена",
        "EVENT_FEE_NONE": "Узнос не патрэбны",
        "EVENT_FEE_PAID": "Узнос ужо аплачаны",
        "EVENT_FEE_NEED_ACCEPT": "Спачатку трэба быць прынятым",
        "EVENT_ORG_MISSING": "Арганізатар не знойдзены",
        "EVENT_FEE_CONFIRM": "Аплаціць узнос за «{title}»?\n\nСума: {price} іскраў\nБаланс: {balance} іскраў",
        "EVENT_FEE_DONE": "Узнос аплачаны!",
        "EVENT_NOT_ENOUGH": "Недастаткова Іскраў. Трэба {need}, у цябе {have}",
        "PREMIUM_ACTIVATED": "Premium актываваны на 1 месяц!",
        "PROFILE_DISABLED_BYE": "Анкета адключана. Да сустрэчы!",
        "REF_NO_REWARDS": "Няма даступных узнагарод",
        "REF_CLAIMED": "Узнагарода атрымана: {reward}",
        "REF_INVITED_LINE": "Запрошана: {count}",
        "BUY_SPARKS_ASK": "Колькі Іскраў хочаш купіць?",
        "BUY_PREMIUM_BTN": "Купіць падпіску за {price} 🌙",
        "WITHDRAW_MIN": "Мінімальная сума вываду — {min} Іскраў",
        "RATING_RESET_FREE": "Рэйтынг скінуты бясплатна (Premium).",
        "RATING_RESET_OK": "Рэйтынг скінуты.",
        "VERIFY_ALREADY": "Ты ўжо верыфікаваны",
        "VERIFY_NEED_CIRCLE": "Дашлі відэапаведамленне (кружок) з тварам, кодам і жэстам.",
        "PAY_NOT_STUB": "Гэта не дэма-плацёж",
        "PAY_ALREADY": "Ужо залічана",
        "EVGROUP_HINT": "Набор закрыты. Стварыце чат — спіс удзельнікаў адпраўлены.",
        "EDIT_FIELD_UNKNOWN": "Невядомае поле",
        "EDIT_ASK_TITLE": "Назва тусоўкі:",
        "EDIT_ASK_CITY": "Горад:",
        "EDIT_ASK_ADDRESS": "Месца:",
        "EDIT_ASK_DATETIME": "Дата і час (напр. 25.07.2026 19:00):",
        "EDIT_ASK_PRICE": "Колькі скідвацца:",
        "EDIT_ASK_DESC": "Апісанне:",
        "EDIT_ASK_PHOTO": "Дашлі новае фота:",

        "PROFILE_OWN": "👋 Імя: {name}, {age}{premium}{verified}\n{bio}\n⚡ Іскры: {sparks}\n🌟 Рэйтынг: {rating}/5\n👥 Вас ацанілі {rated}\n🎉 Тусовак наведаў: {attended}\n😎 Тусовак арганізаваў: {organized}\n{goal}\nПол: {gender}\nКого ацэньваць: {seeking}\nКаму паказвацца: {visible}\n🌆 Горад: {city}",
        "PROFILE_GOAL_OWN": "⚡️Мэта: {title}",
        "PROFILE_OTHER": "{name}, {age}{badges}\n{bio}\n🌟 Рэйтынг: {rating}/5 ({rated})\n🎉 Наведаў: {attended}\n🥳 Арганізаваў: {organized}\n🎯 Мэта: {goal}\n🌆 Горад: {city}",
        "PROFILE_GOAL_OTHER": "{title} · {collected}/{target} (засталося {remaining}, {percent}%)",
        "EVENT_CARD": "🔥 {title}{pin}{boost}\n🏷 {category}\n📍 {city}, {address}\n🕐 {date}, {time}\n👥 {men_label}: {men_count}/{men_needed}  👩 {women_label}: {women_count}/{women_needed}\n💰 {price}{org}\n{description}",
        "EVENT_DEFAULT_CAT": "Тусоўка",
        "EVENT_MEN": "Хлопцы",
        "EVENT_WOMEN": "Дзяўчаты",
        "EVENT_ROLE_ORG": "Арганізатар:\n{meta}",
        "EVENT_ROLE_ATTEND": "Удзельнічаеш:\n{meta}{fee_line}",
        "EVENT_FEE_LINE": "\n💰 Узнос: {price} іскраў",
        "EVENT_FEE_LINE_PAID": "\n💰 Узнос: {price} іскраў · аплачаны ✅",
        "EVENT_FEE_PAID_NOTIFY": "💰 {name} аплаціў(ла) узнос {price} іскраў за «{title}».",
        "EVENT_NEW_APP": "📩 Новая заяўка на «{title}»",
        "EVENT_MANAGE_HEADER": "{mark} Арганізатар: «{title}»\n📍 {city} · {date} {time}",
        "EVENT_GENDER_M": "М",
        "EVENT_GENDER_F": "Ж",
        "MASS_INVITE": "🎉 Запрашэнне на «{title}»\n📍 {city}, {address}\n🕐 {date} {time}\nАдкрыць: {link}",
        "EVENT_CLOSED_ROSTER": "🔒 Набор на «{title}» закрыты.\n\nАрганізатар: {org}\nУдзельнікі:\n{roster}\n\nСтварыце чат і дадайце ўсіх.\nСпасылка: {link}",
        "BUY_SPARKS_TITLE": "Купля Іскраў",
        "BUY_SPARKS_DESC": "Купля {amount} Іскраў",
        "BUY_SPARKS_LABEL": "Іскры",
        "YEARS_ONE": "год",
        "YEARS_FEW": "гады",
        "YEARS_MANY": "гадоў",
        "GENDER_male": "мужчынскі",
        "GENDER_female": "жаночы",
        "GENDER_other": "іншы",
        "SEEKING_men": "мужчынскі",
        "SEEKING_women": "жаночы",
        "SEEKING_both": "абодва",
        "VISIBLE_men": "мужчынскі",
        "VISIBLE_women": "жаночы",
        "VISIBLE_all": "усе",
        "ERR_ONLY_PREMIUM": "Толькі для Premium",
        "ERR_ONLY_ORG": "Толькі арганізатар",
        "ERR_MASS_LIMIT": "Ліміт масавых запрашэнняў вычарпаны",
        "ERR_USER_NOT_FOUND": "Карыстальнік не знойдзены",
        "ERR_FEE_NONE": "Узнос не патрэбны",
        "ERR_FEE_SELF": "Нельга аплаціць сабе",
        "ERR_FEE_PAID": "Узнос ужо аплачаны",
        "ERR_NO_GOAL_SPARKS": "Няма Іскраў для пераводу з мэты",
        "ERR_REWARD_UNAVAILABLE": "Узнагарода недаступная",
        "ERR_WITHDRAW_METHOD": "Няправільны спосаб вываду",
        "ERR_REQUISITES": "Укажы рэквізіты падрабязней",
        "ERR_EVENT_INACTIVE": "Тусоўка не актыўная",
        "ERR_BOOST_ORG": "Толькі арганізатар можа падняць тусоўку",
        "ERR_PIN_ORG": "Толькі арганізатар можа замацаваць тусоўку",
        "ERR_SUPPORT_SPARKS": "Недастаткова Іскраў для падтрымкі",
        "LUMA_PEOPLE_EMPTY": "Нікога не знайшла. Удакладні горад ці інтарэсы.",
        "LUMA_PEOPLE_DONE": "Гэта ўсе анкеты па запыце. Можаш пашукаць яшчэ.",
        "LUMA_PEOPLE_FOUND": "Знайшла людзей:",
        "LUMA_EVENTS_EMPTY": "Тусовак не знайшла. Паспрабуй іншыя словы.",
        "LUMA_EVENTS_DONE": "Гэта ўсе тусоўкі па запыце. Можаш пашукаць яшчэ.",
        "LUMA_EVENTS_FOUND": "Знайшла тусоўкі:",
        "LUMA_EVENT_LINE": "• «{title}» — {city}, {date} {time}\n  {address} · месцы {taken}/{need}",
    },
    "uk": {
        "MENU_TITLE": "Меню:",
        "WITHDRAW_CHOOSE_METHOD": "Як вивести Іскри?\n\n⭐ Stars — на твій акаунт\n💳 Реквізити — карта / телефон",
        "WITHDRAW_AMOUNT": "Скільки Іскор вивести:",
        "WITHDRAW_CREATED_STARS": "Заявка #{id}: {amount} Іскор через Stars. До виплати: {net} (комісія {fee}).\n{status_line}",
        "WITHDRAW_CREATED_REQ": "Заявка #{id}: {amount} Іскор на реквізити. До виплати: {net} (комісія {fee}).",
        "WITHDRAW_STARS_OK": "✅ Stars виплачено ({gifts} подарунків, {stars}⭐).",
        "WITHDRAW_STARS_PENDING": "⏳ Автовиплата не пройшла: {error}",
        "WITHDRAW_ASK_REQUISITES": "Вкажи реквізити. Сума: {amount} Іскор",
        "EVENT_ASK_CATEGORY": "Обери тематику тусовки:",
        "EVENT_CREATED": "Тусовку «{title}» створено!",
        "EVENT_ASK_TITLE": "Назва тусовки:",
        "EVENT_ASK_CITY": "Місто:",
        "EVENT_ASK_ADDRESS": "Місце:",
        "EVENT_ASK_DATETIME": "Дата і час (напр. 25.07.2026 19:00):",
        "EVENT_ASK_PRICE": "Скільки скидатися:",
        "EVENT_ASK_MEN": "Скільки хлопців:",
        "EVENT_ASK_WOMEN": "Скільки дівчат:",
        "EVENT_ASK_PHOTO": "Фото тусовки:",
        "EVENT_ASK_DESC": "Опис:",
        "NO_GOAL": "У тебе поки немає цілі.",
        "PHOTO_ASK": "Надішли своє фото",
        "CITY_ASK": "З якого ти міста?",
        "SPARKS_TRANSFERRED": "Переведено {amount} Іскор на баланс.",
        "EVENT_NOT_FOUND": "Тусовку не знайдено.",
        "EVENT_CLOSED": "Тусовка «{title}» вже закрита.",
        "EVENT_NONE": "У тебе поки немає тусовок.",
        "EVENT_PICK": "Обери тусовку:",
        "EVENT_EMPTY_CAT": "Поки немає тусовок у цій категорії.",
        "EVENT_EMPTY_TODAY": "На сьогодні тусовок поки немає.",
        "EVENT_EMPTY_NEAR": "Поруч тусовок немає. Вкажи місто в профілі або заглянь пізніше.",
        "EVENT_NO_MORE": "Більше тусовок немає.",
        "EVENT_SHARE": "Посилання:\n{link}",
        "EVENT_NO_APPS": "Немає заявок.",
        "EVENT_INVITE_PEOPLE": "Запросити людей:",
        "EVENT_PARTS_EMPTY": "Учасники «{title}»:\n\nПоки нікого.",
        "EVENT_PARTS_LIST": "Учасники «{title}» ({count}):",
        "EVENT_EDIT_WHAT": "Що змінити в «{title}»?",
        "EVENT_SAVED": "Збережено.",
        "EVENT_PHOTO_UPDATED": "Фото оновлено.",
        "EVENT_NEED_TEXT": "Зараз потрібен текст.",
        "EVENT_NEED_PHOTO": "Надішли фото.",
        "EVENT_APP_SENT": "Заявку надіслано!",
        "EVENT_APP_ALREADY": "Ти вже подав заявку",
        "EVENT_APP_ACCEPTED_STATUS": "Ти вже у списку учасників",
        "EVENT_APP_PENDING": "Ти вже подав заявку",
        "EVENT_APP_REJECTED_STATUS": "Заявку раніше відхилено",
        "EVENT_FEE_NONE": "Внесок не потрібен",
        "EVENT_FEE_PAID": "Внесок вже оплачено",
        "EVENT_FEE_NEED_ACCEPT": "Спочатку потрібно бути прийнятим",
        "EVENT_ORG_MISSING": "Організатора не знайдено",
        "EVENT_FEE_CONFIRM": "Оплатити внесок за «{title}»?\n\nСума: {price} іскор\nБаланс: {balance} іскор",
        "EVENT_FEE_DONE": "Внесок оплачено!",
        "EVENT_NOT_ENOUGH": "Недостатньо Іскор. Потрібно {need}, у тебе {have}",
        "PREMIUM_ACTIVATED": "Premium активовано на 1 місяць!",
        "PROFILE_DISABLED_BYE": "Анкету вимкнено. До зустрічі!",
        "REF_NO_REWARDS": "Немає доступних нагород",
        "REF_CLAIMED": "Нагороду отримано: {reward}",
        "REF_INVITED_LINE": "Запрошено: {count}",
        "BUY_SPARKS_ASK": "Скільки Іскор хочеш купити?",
        "BUY_PREMIUM_BTN": "Купити підписку за {price} 🌙",
        "WITHDRAW_MIN": "Мінімальна сума виводу — {min} Іскор",
        "RATING_RESET_FREE": "Рейтинг скинуто безкоштовно (Premium).",
        "RATING_RESET_OK": "Рейтинг скинуто.",
        "VERIFY_ALREADY": "Ти вже верифікований",
        "VERIFY_NEED_CIRCLE": "Надішли відеоповідомлення (кружок) з обличчям, кодом і жестом.",
        "PAY_NOT_STUB": "Це не демо-платіж",
        "PAY_ALREADY": "Вже зараховано",
        "EVGROUP_HINT": "Набір закрито. Створіть чат — список учасників надіслано.",
        "EDIT_FIELD_UNKNOWN": "Невідоме поле",
        "EDIT_ASK_TITLE": "Назва тусовки:",
        "EDIT_ASK_CITY": "Місто:",
        "EDIT_ASK_ADDRESS": "Місце:",
        "EDIT_ASK_DATETIME": "Дата і час (напр. 25.07.2026 19:00):",
        "EDIT_ASK_PRICE": "Скільки скидатися:",
        "EDIT_ASK_DESC": "Опис:",
        "EDIT_ASK_PHOTO": "Надішли нове фото:",

        "PROFILE_OWN": "👋 Імʼя: {name}, {age}{premium}{verified}\n{bio}\n⚡ Іскри: {sparks}\n🌟 Рейтинг: {rating}/5\n👥 Вас оцінили {rated}\n🎉 Відвідав тусовок: {attended}\n😎 Організував: {organized}\n{goal}\nСтать: {gender}\nКого оцінювати: {seeking}\nКому показуватися: {visible}\n🌆 Місто: {city}",
        "PROFILE_GOAL_OWN": "⚡️Ціль: {title}",
        "PROFILE_OTHER": "{name}, {age}{badges}\n{bio}\n🌟 Рейтинг: {rating}/5 ({rated})\n🎉 Відвідав: {attended}\n🥳 Організував: {organized}\n🎯 Ціль: {goal}\n🌆 Місто: {city}",
        "PROFILE_GOAL_OTHER": "{title} · {collected}/{target} (залишилось {remaining}, {percent}%)",
        "EVENT_CARD": "🔥 {title}{pin}{boost}\n🏷 {category}\n📍 {city}, {address}\n🕐 {date}, {time}\n👥 {men_label}: {men_count}/{men_needed}  👩 {women_label}: {women_count}/{women_needed}\n💰 {price}{org}\n{description}",
        "EVENT_DEFAULT_CAT": "Тусовка",
        "EVENT_MEN": "Хлопці",
        "EVENT_WOMEN": "Дівчата",
        "EVENT_ROLE_ORG": "Організатор:\n{meta}",
        "EVENT_ROLE_ATTEND": "Береш участь:\n{meta}{fee_line}",
        "EVENT_FEE_LINE": "\n💰 Внесок: {price} іскор",
        "EVENT_FEE_LINE_PAID": "\n💰 Внесок: {price} іскор · оплачено ✅",
        "EVENT_FEE_PAID_NOTIFY": "💰 {name} оплатив(ла) внесок {price} іскор за «{title}».",
        "EVENT_NEW_APP": "📩 Нова заявка на «{title}»",
        "EVENT_MANAGE_HEADER": "{mark} Організатор: «{title}»\n📍 {city} · {date} {time}",
        "EVENT_GENDER_M": "Ч",
        "EVENT_GENDER_F": "Ж",
        "MASS_INVITE": "🎉 Запрошення на «{title}»\n📍 {city}, {address}\n🕐 {date} {time}\nВідкрити: {link}",
        "EVENT_CLOSED_ROSTER": "🔒 Набір на «{title}» закрито.\n\nОрганізатор: {org}\nУчасники:\n{roster}\n\nСтворіть чат і додайте всіх.\nПосилання: {link}",
        "BUY_SPARKS_TITLE": "Купівля Іскор",
        "BUY_SPARKS_DESC": "Купівля {amount} Іскор",
        "BUY_SPARKS_LABEL": "Іскри",
        "YEARS_ONE": "рік",
        "YEARS_FEW": "роки",
        "YEARS_MANY": "років",
        "GENDER_male": "чоловіча",
        "GENDER_female": "жіноча",
        "GENDER_other": "інша",
        "SEEKING_men": "чоловічу",
        "SEEKING_women": "жіночу",
        "SEEKING_both": "обидві",
        "VISIBLE_men": "чоловічій",
        "VISIBLE_women": "жіночій",
        "VISIBLE_all": "всім",
        "ERR_ONLY_PREMIUM": "Тільки для Premium",
        "ERR_ONLY_ORG": "Тільки організатор",
        "ERR_MASS_LIMIT": "Ліміт масових запрошень вичерпано",
        "ERR_USER_NOT_FOUND": "Користувача не знайдено",
        "ERR_FEE_NONE": "Внесок не потрібен",
        "ERR_FEE_SELF": "Не можна оплатити собі",
        "ERR_FEE_PAID": "Внесок вже оплачено",
        "ERR_NO_GOAL_SPARKS": "Немає Іскор для переказу з цілі",
        "ERR_REWARD_UNAVAILABLE": "Нагорода недоступна",
        "ERR_WITHDRAW_METHOD": "Невірний спосіб виводу",
        "ERR_REQUISITES": "Вкажи реквізити докладніше",
        "ERR_EVENT_INACTIVE": "Тусовка не активна",
        "ERR_BOOST_ORG": "Тільки організатор може підняти тусовку",
        "ERR_PIN_ORG": "Тільки організатор може закріпити тусовку",
        "ERR_SUPPORT_SPARKS": "Недостатньо Іскор для підтримки",
        "LUMA_PEOPLE_EMPTY": "Нікого не знайшла. Уточни місто або інтереси.",
        "LUMA_PEOPLE_DONE": "Це всі анкети за запитом. Можеш пошукати ще.",
        "LUMA_PEOPLE_FOUND": "Знайшла людей:",
        "LUMA_EVENTS_EMPTY": "Тусовок не знайшла. Спробуй інші слова.",
        "LUMA_EVENTS_DONE": "Це всі тусовки за запитом. Можеш пошукати ще.",
        "LUMA_EVENTS_FOUND": "Знайшла тусовки:",
        "LUMA_EVENT_LINE": "• «{title}» — {city}, {date} {time}\n  {address} · місця {taken}/{need}",
    },
    "kk": {
        "MENU_TITLE": "Меню:",
        "WITHDRAW_CHOOSE_METHOD": "Ұшқынды қалай шығарамыз?\n\n⭐ Stars — аккаунтыңа\n💳 Реквизиттер — карта / телефон",
        "WITHDRAW_AMOUNT": "Қанша Ұшқын шығару керек:",
        "WITHDRAW_CREATED_STARS": "Өтінім #{id}: {amount} Ұшқын Stars арқылы. Төлем: {net} (комиссия {fee}).\n{status_line}",
        "WITHDRAW_CREATED_REQ": "Өтінім #{id}: {amount} Ұшқын реквизиттерге. Төлем: {net} (комиссия {fee}).",
        "WITHDRAW_STARS_OK": "✅ Stars төленді ({gifts} сыйлық, {stars}⭐).",
        "WITHDRAW_STARS_PENDING": "⏳ Автотөлем өтпеді: {error}",
        "WITHDRAW_ASK_REQUISITES": "Реквизиттерді жаз. Сома: {amount} Ұшқын",
        "EVENT_ASK_CATEGORY": "Тусовка тақырыбын таңда:",
        "EVENT_CREATED": "«{title}» тусовкасы жасалды!",
        "EVENT_ASK_TITLE": "Тусовка атауы:",
        "EVENT_ASK_CITY": "Қала:",
        "EVENT_ASK_ADDRESS": "Орын:",
        "EVENT_ASK_DATETIME": "Күні мен уақыты (мыс. 25.07.2026 19:00):",
        "EVENT_ASK_PRICE": "Қанша жинау:",
        "EVENT_ASK_MEN": "Қанша жігіт:",
        "EVENT_ASK_WOMEN": "Қанша қыз:",
        "EVENT_ASK_PHOTO": "Тусовка фотосы:",
        "EVENT_ASK_DESC": "Сипаттама:",
        "NO_GOAL": "Әзірге мақсат жоқ.",
        "PHOTO_ASK": "Фотоңды жібер",
        "CITY_ASK": "Қай қаладансың?",
        "SPARKS_TRANSFERRED": "{amount} Ұшқын балансқа аударылды.",
        "EVENT_NOT_FOUND": "Тусовка табылмады.",
        "EVENT_CLOSED": "«{title}» тусовкасы жабылған.",
        "EVENT_NONE": "Әзірге тусовкалар жоқ.",
        "EVENT_PICK": "Тусовканы таңда:",
        "EVENT_EMPTY_CAT": "Бұл санатта тусовка жоқ.",
        "EVENT_EMPTY_TODAY": "Бүгінге тусовка әзірге жоқ.",
        "EVENT_EMPTY_NEAR": "Жақында тусовка жоқ. Профильде қаланы көрсет немесе кейінірек қара.",
        "EVENT_NO_MORE": "Тусовка қалмады.",
        "EVENT_SHARE": "Сілтеме:\n{link}",
        "EVENT_NO_APPS": "Өтінімдер жоқ.",
        "EVENT_INVITE_PEOPLE": "Адамдарды шақыру:",
        "EVENT_PARTS_EMPTY": "«{title}» қатысушылары:\n\nӘзірге ешкім жоқ.",
        "EVENT_PARTS_LIST": "«{title}» қатысушылары ({count}):",
        "EVENT_EDIT_WHAT": "«{title}» — нені өзгерту?",
        "EVENT_SAVED": "Сақталды.",
        "EVENT_PHOTO_UPDATED": "Фото жаңартылды.",
        "EVENT_NEED_TEXT": "Қазір мәтін қажет.",
        "EVENT_NEED_PHOTO": "Фото жібер.",
        "EVENT_APP_SENT": "Өтінім жіберілді!",
        "EVENT_APP_ALREADY": "Өтінім бұрын жіберілген",
        "EVENT_APP_ACCEPTED_STATUS": "Сен тізімде бар",
        "EVENT_APP_PENDING": "Өтінім бұрын жіберілген",
        "EVENT_APP_REJECTED_STATUS": "Өтінім бұрын қабылданбаған",
        "EVENT_FEE_NONE": "Жарна қажет емес",
        "EVENT_FEE_PAID": "Жарна төленген",
        "EVENT_FEE_NEED_ACCEPT": "Алдымен қабылдану керек",
        "EVENT_ORG_MISSING": "Ұйымдастырушы табылмады",
        "EVENT_FEE_CONFIRM": "«{title}» жарнасын төлеу?\n\nСома: {price} ұшқын\nБаланс: {balance} ұшқын",
        "EVENT_FEE_DONE": "Жарна төленді!",
        "EVENT_NOT_ENOUGH": "Ұшқын жеткіліксіз. Қажет: {need}, бар: {have}",
        "PREMIUM_ACTIVATED": "Premium 1 айға қосылды!",
        "PROFILE_DISABLED_BYE": "Анкета өшірілді. Кездескенше!",
        "REF_NO_REWARDS": "Қолжетімді марапат жоқ",
        "REF_CLAIMED": "Марапат алынды: {reward}",
        "REF_INVITED_LINE": "Шақырылды: {count}",
        "BUY_SPARKS_ASK": "Қанша Ұшқын сатып аласың?",
        "BUY_PREMIUM_BTN": "Жазылым сатып алу — {price} 🌙",
        "WITHDRAW_MIN": "Шығарудың ең аз сомасы — {min} Ұшқын",
        "RATING_RESET_FREE": "Рейтинг тегін тасталды (Premium).",
        "RATING_RESET_OK": "Рейтинг тасталды.",
        "VERIFY_ALREADY": "Сен верификациядан өткенсің",
        "VERIFY_NEED_CIRCLE": "Бет, код, ишара көрсетіп дөңгелек видео жібер.",
        "PAY_NOT_STUB": "Бұл демо-төлем емес",
        "PAY_ALREADY": "Бұрын есептелген",
        "EVGROUP_HINT": "Жинақ жабылды. Чат жасаңыз — қатысушылар тізімі жіберілді.",
        "EDIT_FIELD_UNKNOWN": "Белгісіз өріс",
        "EDIT_ASK_TITLE": "Тусовка атауы:",
        "EDIT_ASK_CITY": "Қала:",
        "EDIT_ASK_ADDRESS": "Орын:",
        "EDIT_ASK_DATETIME": "Күні мен уақыты (мыс. 25.07.2026 19:00):",
        "EDIT_ASK_PRICE": "Қанша жинау:",
        "EDIT_ASK_DESC": "Сипаттама:",
        "EDIT_ASK_PHOTO": "Жаңа фото жібер:",

        "PROFILE_OWN": "👋 Аты: {name}, {age}{premium}{verified}\n{bio}\n⚡ Ұшқын: {sparks}\n🌟 Рейтинг: {rating}/5\n👥 Сізді бағалады: {rated}\n🎉 Қатысты: {attended}\n😎 Ұйымдастырды: {organized}\n{goal}\nЖынысы: {gender}\nКімді бағалау: {seeking}\nКімге көрсету: {visible}\n🌆 Қала: {city}",
        "PROFILE_GOAL_OWN": "⚡️Мақсат: {title}",
        "PROFILE_OTHER": "{name}, {age}{badges}\n{bio}\n🌟 Рейтинг: {rating}/5 ({rated})\n🎉 Қатысты: {attended}\n🥳 Ұйымдастырды: {organized}\n🎯 Мақсат: {goal}\n🌆 Қала: {city}",
        "PROFILE_GOAL_OTHER": "{title} · {collected}/{target} (қалды {remaining}, {percent}%)",
        "EVENT_CARD": "🔥 {title}{pin}{boost}\n🏷 {category}\n📍 {city}, {address}\n🕐 {date}, {time}\n👥 {men_label}: {men_count}/{men_needed}  👩 {women_label}: {women_count}/{women_needed}\n💰 {price}{org}\n{description}",
        "EVENT_DEFAULT_CAT": "Тусовка",
        "EVENT_MEN": "Жігіттер",
        "EVENT_WOMEN": "Қыздар",
        "EVENT_ROLE_ORG": "Ұйымдастырушы:\n{meta}",
        "EVENT_ROLE_ATTEND": "Қатысасың:\n{meta}{fee_line}",
        "EVENT_FEE_LINE": "\n💰 Жарна: {price} ұшқын",
        "EVENT_FEE_LINE_PAID": "\n💰 Жарна: {price} ұшқын · төленді ✅",
        "EVENT_FEE_PAID_NOTIFY": "💰 {name} «{title}» үшін {price} ұшқын жарна төледі.",
        "EVENT_NEW_APP": "📩 «{title}» жаңа өтінім",
        "EVENT_MANAGE_HEADER": "{mark} Ұйымдастырушы: «{title}»\n📍 {city} · {date} {time}",
        "EVENT_GENDER_M": "Е",
        "EVENT_GENDER_F": "Ә",
        "MASS_INVITE": "🎉 «{title}» шақыру\n📍 {city}, {address}\n🕐 {date} {time}\nАшу: {link}",
        "EVENT_CLOSED_ROSTER": "🔒 «{title}» жинақ жабылды.\n\nҰйымдастырушы: {org}\nҚатысушылар:\n{roster}\n\nТоптық чат жасап, бәрін қосыңыз.\nСілтеме: {link}",
        "BUY_SPARKS_TITLE": "Ұшқын сатып алу",
        "BUY_SPARKS_DESC": "{amount} ұшқын сатып алу",
        "BUY_SPARKS_LABEL": "Ұшқын",
        "YEARS_ONE": "жас",
        "YEARS_FEW": "жас",
        "YEARS_MANY": "жас",
        "GENDER_male": "ер",
        "GENDER_female": "әйел",
        "GENDER_other": "басқа",
        "SEEKING_men": "ерлерді",
        "SEEKING_women": "әйелдерді",
        "SEEKING_both": "екеуін",
        "VISIBLE_men": "ерлерге",
        "VISIBLE_women": "әйелдерге",
        "VISIBLE_all": "барлығына",
        "ERR_ONLY_PREMIUM": "Тек Premium үшін",
        "ERR_ONLY_ORG": "Тек ұйымдастырушы",
        "ERR_MASS_LIMIT": "Жаппай шақыру лимиті бітті",
        "ERR_USER_NOT_FOUND": "Пайдаланушы табылмады",
        "ERR_FEE_NONE": "Жарна қажет емес",
        "ERR_FEE_SELF": "Өзіне төлеуге болмайды",
        "ERR_FEE_PAID": "Жарна төленген",
        "ERR_NO_GOAL_SPARKS": "Мақсаттан аударатын ұшқын жоқ",
        "ERR_REWARD_UNAVAILABLE": "Марапат қолжетімсіз",
        "ERR_WITHDRAW_METHOD": "Қате шығару әдісі",
        "ERR_REQUISITES": "Реквизиттерді толығырақ көрсетіңіз",
        "ERR_EVENT_INACTIVE": "Тусовка белсенді емес",
        "ERR_BOOST_ORG": "Тек ұйымдастырушы көтере алады",
        "ERR_PIN_ORG": "Тек ұйымдастырушы бекіте алады",
        "ERR_SUPPORT_SPARKS": "Қолдауға ұшқын жетпейді",
        "LUMA_PEOPLE_EMPTY": "Ешкім табылмады. Қаланы немесе қызығушылықты нақтыла.",
        "LUMA_PEOPLE_DONE": "Сұрау бойынша барлық анкета осы. Қайта іздеуге болады.",
        "LUMA_PEOPLE_FOUND": "Адамдар табылды:",
        "LUMA_EVENTS_EMPTY": "Тусовка табылмады. Басқа сөздерді байқап көр.",
        "LUMA_EVENTS_DONE": "Сұрау бойынша барлық тусовка осы. Қайта іздеуге болады.",
        "LUMA_EVENTS_FOUND": "Тусовкалар табылды:",
        "LUMA_EVENT_LINE": "• «{title}» — {city}, {date} {time}\n  {address} · орын {taken}/{need}",
    },
}


def lbl(lang_or_user, key: str, group: str = "inline") -> str:
    lang = normalize_lang(lang_or_user if isinstance(lang_or_user, str) else lang_of(lang_or_user))
    bucket = MENU if group == "menu" else INLINE
    row = bucket.get(key) or {}
    return row.get(lang) or row.get(DEFAULT_LANG) or key


def category_label(name: str, lang_or_user, emoji: str = "") -> str:
    """Локализованная подпись категории по каноническому имени из БД."""
    lang = normalize_lang(lang_or_user if isinstance(lang_or_user, str) else lang_of(lang_or_user))
    row = EVENT_CATEGORIES.get(name) or {}
    label = row.get(lang) or row.get(DEFAULT_LANG) or name
    emoji = (emoji or "").strip()
    return f"{emoji} {label}".strip() if emoji else label


def localize_stored_category(raw: str | None, lang_or_user) -> str:
    """Перевести category с карточки события (имя или «emoji имя»)."""
    lang = normalize_lang(lang_or_user if isinstance(lang_or_user, str) else lang_of(lang_or_user))
    if not raw or not str(raw).strip():
        return tx(lang, "EVENT_DEFAULT_CAT")
    text = str(raw).strip()
    if text in EVENT_CATEGORIES:
        return category_label(text, lang)
    # Сортируем по длине, чтобы «На хату» не перебивалось короче
    for name in sorted(EVENT_CATEGORIES.keys(), key=len, reverse=True):
        if text == name or text.endswith(name) or text.endswith(f" {name}"):
            prefix = text[: -len(name)].strip()
            return category_label(name, lang, emoji=prefix)
    return text


def tx(lang_or_user, key: str, **kwargs) -> str:
    """Доп. UI-тексты (не из основного TEXTS)."""
    from bot.texts.i18n import t as base_t

    lang = normalize_lang(lang_or_user if isinstance(lang_or_user, str) else lang_of(lang_or_user))
    text = (EXTRA_TEXTS.get(lang) or {}).get(key) or (EXTRA_TEXTS.get(DEFAULT_LANG) or {}).get(key)
    if text:
        try:
            return text.format(**kwargs) if kwargs else text
        except (KeyError, ValueError):
            return text
    return base_t(lang, key, **kwargs)


def all_menu_labels(action: str) -> set[str]:
    row = MENU.get(action) or {}
    labels = set(row.values())
    labels |= _MENU_LEGACY.get(action, set())
    return labels


def all_main_menu_texts() -> set[str]:
    """Все подписи reply-кнопок главного меню (для роутинга и throttle)."""
    texts: set[str] = set()
    for action in ("rate", "events", "profile", "goals", "luma", "menu"):
        texts |= all_menu_labels(action)
    return texts


# Старые подписи без эмодзи — пока у пользователей не обновилась клавиатура
_MENU_LEGACY: dict[str, set[str]] = {
    "rate": {"Оценивать", "Ацэньваць", "Оцінювати", "Бағалау"},
    "events": {"Тусовки", "Тусоўкі", "Тусовкалар"},
    "profile": {"Профиль", "Профіль"},
    "goals": {"Цели", "Мэты", "Цілі", "Мақсаттар"},
    "luma": {"Лума"},
    "menu": set(),
}


def resolve_menu_action(text: str) -> str | None:
    for action, row in MENU.items():
        if text in row.values() or text in _MENU_LEGACY.get(action, set()):
            return action
    return None


# Русские / кодовые сообщения сервисов → ключи EXTRA_TEXTS / TEXTS
_SERVICE_ERR_MAP: dict[str, str] = {
    "Недостаточно Искр": "ERR_NOT_ENOUGH_SPARKS",
    "Недостаточно Искр для поддержки": "ERR_SUPPORT_SPARKS",
    "Пользователь не найден": "ERR_USER_NOT_FOUND",
    "Взнос не требуется": "ERR_FEE_NONE",
    "Нельзя оплатить взнос самому себе": "ERR_FEE_SELF",
    "Взнос уже оплачен": "ERR_FEE_PAID",
    "Нет Искр для перевода с цели": "ERR_NO_GOAL_SPARKS",
    "Награда недоступна": "ERR_REWARD_UNAVAILABLE",
    "Неверный способ вывода": "ERR_WITHDRAW_METHOD",
    "Укажи реквизиты для перевода подробнее": "ERR_REQUISITES",
    "Только для Premium": "ERR_ONLY_PREMIUM",
    "Только организатор": "ERR_ONLY_ORG",
    "Лимит массовых приглашений исчерпан": "ERR_MASS_LIMIT",
    "Тусовка не активна": "ERR_EVENT_INACTIVE",
    "Только организатор может поднять тусовку": "ERR_BOOST_ORG",
    "Только организатор может закрепить тусовку": "ERR_PIN_ORG",
    "AI_LIMIT": "LUMA_LIMIT",
}


def service_err(lang_or_user, err: BaseException | str) -> str:
    """Локализовать типичные ValueError из сервисов."""
    raw = str(err)
    key = _SERVICE_ERR_MAP.get(raw)
    if key:
        return tx(lang_or_user, key)
    if raw.startswith("Минимальная сумма вывода"):
        return tx(lang_or_user, "WITHDRAW_MIN", min=raw.split("—")[-1].strip().split()[0] if "—" in raw else "")
    return raw
